### ISSUE TITLE
Add autocomplete to whispers

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#27] opened 2017-07-24 16:54 UTC
http://jqueryui.com/autocomplete/
trigger autocomplete for usernames when a user hits @ 

Actually this framework probably has more features and looks like it's actively maintained:
https://github.com/LeaVerou/awesomplete

**Comment by studyhog** [comment] 2019-12-20 07:15
Duplicate of https://github.com/openanswer/OpenAnswer/issues/271

**Closed** 2019-12-20 07:14 UTC
