### ISSUE TITLE
New section for DMs

### ISSUE THREAD

**Issue by EntersNewUserName79** [openanswer/OpenAnswer#17] opened 2017-06-02 07:03 UTC
Don't know if its just me, but whenever I refresh the page, the dm disappears.

**Comment by openanswer** [comment] 2017-06-02 14:50
It's not just you, those aren't really dms - more like whispers. We don't persist them in the database, so whenever you refresh they're gone. We probably need to add actual direct messaging.

**Comment by openanswer** [comment] 2017-06-02 18:46
Actually we might get away with existing style DMs just by saving them to local storage. This would only persist on the machine and still disappear on cache clear.

**Comment by studyhog** [comment] 2019-12-11 18:58
Duplicate of #13

**Closed by studyhog** 2019-12-11 18:58 UTC
Labels: enhancement, question
