### ISSUE TITLE
Direct messages

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#13] opened 2017-06-01 20:49 UTC
Or whispering... Add the ability to send someone a message that's only seen by the recipient.

**Comment by openanswer** [comment] 2017-06-01 20:50
This is now complete, you can use @username to whisper a person.

These whispers can only be seen by you and the sender, aren't persisted to the database and disappear when you refresh your browser tab.

If you allow us to send you notifications, whispers alos notify you.

**Comment by openanswer** [comment] 2018-04-25 14:45
New layout does not support this. We need to reimplement/readd support for this.

**Comment by studyhog** [comment] 2019-11-27 09:27
DMs will just be group chats with 2 people.

**Comment by studyhog** [comment] 2019-12-11 18:58
https://github.com/openanswer/OpenAnswer/issues/17
Relevant note from the issue linked:
Actually we might get away with existing style DMs just by saving them to local storage. This would only persist on the machine and still disappear on cache clear.

**Comment by studyhog** [comment] 2019-12-20 07:18
Now duplicate of https://github.com/openanswer/OpenAnswer/issues/285

**Closed by studyhog** 2019-12-20 07:18 UTC
Labels: enhancement
